CREATE DATABASE universe;
-- prettier-ignore
\c universe;
-- prettier-ignore
-- CREATE TABLE galaxy_type(galaxy_type_id INT GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY, name VARCHAR(64) UNIQUE NOT NULL);
CREATE TABLE galaxy_type(galaxy_type_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name VARCHAR(64) UNIQUE NOT NULL,description TEXT NOT NULL);

CREATE TABLE galaxy(
    galaxy_id serial PRIMARY KEY,
    name VARCHAR(64) UNIQUE NOT NULL,
    description TEXT NOT NULL,
    has_life BOOLEAN,
    is_spherical BOOLEAN,
    age_in_millions_of_years NUMERIC(10, 2),
    galaxy_types INT,
    distance_from_earth INT
);
CREATE TABLE star(
    star_id serial PRIMARY KEY,
    galaxy_id SERIAL NOT NULL REFERENCES galaxy(galaxy_id),
    name VARCHAR(64) UNIQUE NOT NULL,
    description TEXT NOT NULL,
    is_spherical BOOLEAN,
    distance_from_earth INT
);
CREATE TABLE planet(
    planet_id serial PRIMARY KEY,
    star_id SERIAL NOT NULL REFERENCES star(star_id),
    name VARCHAR(64) UNIQUE NOT NULL,
    description TEXT NOT NULL,
    is_spherical BOOLEAN,
    distance_from_earth INT,
    planet_type INT
);
CREATE TABLE moon(
    moon_id serial PRIMARY KEY,
    planet_id SERIAL NOT NULL REFERENCES planet(planet_id),
    name VARCHAR(64) UNIQUE NOT NULL,
    description TEXT NOT NULL,
    is_spherical BOOLEAN
);

INSERT INTO galaxy_type(name,description)
VALUES
("spherical","have't decided what to write yet"),
("oval","have't decided what to write yet"),
("irregular","have't decided what to write yet");

-- INSERT mock data to galaxy;
INSERT INTO galaxy(
        name,
        description,
        has_life,
        is_spherical,
        age_in_millions_of_years,
        galaxy_types,
        distance_from_earth
    )
VALUES (
        '1Milky Way',
        'one of the most famous galaxies',
        true,
        true,
        100,
        1,
        100
    ),
    (
        '2Milky Way',
        'one of the most famous galaxies',
        true,
        true,
        100,
        1,
        100
    ),
    (
        '3Milky Way',
        'one of the most famous galaxies',
        true,
        true,
        100,
        1,
        100
    ),
    (
        '4Milky Way',
        'one of the most famous galaxies',
        true,
        true,
        100,
        1,
        100
    ),
    (
        '5Milky Way',
        'one of the most famous galaxies',
        true,
        true,
        100,
        1,
        100
    ),
    (
        '6Milky Way',
        'one of the most famous galaxies',
        true,
        true,
        100,
        1,
        100
    );
-- for star table;
INSERT INTO star(
    galaxy_id,
        name,
        description,
        is_spherical,
        distance_from_earth
    )
VALUES (1,'1sun', 'one of the most famous stars', true, 1),
    (1,'2sun', 'one of the most famous stars', true, 1),
    (1,'3sun', 'one of the most famous stars', true, 1),
    (1,'4sun', 'one of the most famous stars', true, 1),
    (1,'5sun', 'one of the most famous stars', true, 1),
    (1,'6sun', 'one of the most famous stars', true, 1);

INSERT INTO planet(
    star_id,
    name,
    description,
    is_spherical,
    distance_from_earth,
    planet_type
)
VALUES
(1,'1earth','our hometown',true,0,1),
(1,'2earth','our hometown',true,0,1),
(1,'3earth','our hometown',true,0,1),
(1,'4earth','our hometown',true,0,1),
(1,'5earth','our hometown',true,0,1),
(1,'6earth','our hometown',true,0,1),
(1,'16earth','our hometown',true,0,1),
(1,'26earth','our hometown',true,0,1),
(1,'36earth','our hometown',true,0,1),
(1,'46earth','our hometown',true,0,1),
(1,'56earth','our hometown',true,0,1),
(1,'66earth','our hometown',true,0,1)
;

INSERT INTO moon(
    planet_id,name,description,is_spherical
)
VALUES
(1,'1lunar','one of the most famous moon',true),
(1,'2lunar','one of the most famous moon',true),
(1,'3lunar','one of the most famous moon',true),
(1,'4lunar','one of the most famous moon',true),
(1,'5lunar','one of the most famous moon',true),
(1,'6lunar','one of the most famous moon',true),
(1,'16lunar','one of the most famous moon',true),
(1,'26lunar','one of the most famous moon',true),
(1,'36lunar','one of the most famous moon',true),
(1,'46lunar','one of the most famous moon',true),
(1,'56lunar','one of the most famous moon',true),
(1,'66lunar','one of the most famous moon',true),
(1,'76lunar','one of the most famous moon',true),
(1,'86lunar','one of the most famous moon',true),
(1,'96lunar','one of the most famous moon',true),
(1,'106lunar','one of the most famous moon',true),
(1,'116lunar','one of the most famous moon',true),
(1,'126lunar','one of the most famous moon',true),
;